# Generated by Django 3.1.1 on 2020-09-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_remove_requirements_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.ngos'),
        ),
    ]
