# Generated by Django 3.1.1 on 2020-09-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_requirements_donated_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('undone', 'undone')], max_length=200, null=True),
        ),
    ]
