# Generated by Django 3.1.1 on 2020-09-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_requirements_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='status',
        ),
    ]
