# Generated by Django 3.1.1 on 2020-09-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_donor_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='address',
        ),
    ]
