# Generated by Django 3.1.1 on 2020-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200926_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
