# Generated by Django 3.1.1 on 2020-09-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_ngo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='logo',
        ),
    ]
