# Generated by Django 3.1.1 on 2020-09-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200926_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='owner_name',
            new_name='ngo_name',
        ),
    ]
