# Generated by Django 3.1.1 on 2020-09-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200926_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
