# Generated by Django 4.0.4 on 2022-05-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_ngo_aim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='purpose',
        ),
    ]
