# Generated by Django 4.0.1 on 2022-01-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200927_0207'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ngo'),
        ),
    ]
