# Generated by Django 4.0.1 on 2022-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_requirements_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='category',
            field=models.CharField(blank=True, choices=[('medicine', 'medicine'), ('equipment', 'equipment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='donation_count',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='initial_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
