# Generated by Django 4.0.4 on 2022-04-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_requirements_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Medicine'), ('F', 'Food'), ('C', 'Clothing'), ('S', 'Stationary')], max_length=20, null=True),
        ),
    ]
