# Generated by Django 4.0.4 on 2022-04-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_requirements_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='initial_count',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='donation_count',
        ),
    ]
